services:
  node-red:
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - ./node-red-data:/data
      # - ./node-red-data/flash_files:/data/flash_files
      - ./stm32_bin_files:/data/flash_files
      - /dev:/dev
      - /dev/serial/by-id:/dev/serial/by-id
    devices:
      - /dev:/dev
    group_add:
      - dialout
    privileged: true

  # Using mongdb version 4.4.29 so that it will run without a CPU that does not support AVX 
  mongodb:
    image: mongo:4.4.29-focal
    ports:
      - 27017:27017
        #environment:
        #- MONGO_INITDB_ROOT_USERNAME: ""
        #- MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - ./mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      #ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  stm32_flash_api:
    #    image: stm32_flash_api:v0.3
    image: stm32_flash_api:2.4
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      #- ./stm32-data:/home/ubuntu
      # - ./node-red-data/flash_files:/home/ubuntu
      - ./stm32_bin_files:/home/ubuntu
      - /dev:/dev
    devices:
      - /dev:/dev
    privileged: true #added to allow access to USB connected devices

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - ./stm32_bin_files:/srv
      - ./filebrowser_database:/database
      - ./filebrowser_config:/config
